name:                create-module
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/mjhopkins/create-module#readme
license:             BSD3
author:              Mark Hopkins
maintainer:          markjohnhopkins@gmail.com
copyright:           Mark Hopkins
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - directory
  - extra
  - filepath
  - mtl
  - regex-tdfa
  - transformers

ghc-options:
  - -j
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wpartial-fields
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Werror=inaccessible-code
  - -Werror=overlapping-patterns
  - -Werror=incomplete-patterns
  - -Werror=missing-methods
  - -Werror=missing-fields
  - -fhide-source-paths
  - -fno-warn-name-shadowing

default-extensions: []

library:
  source-dirs: src

_executable-ghc-options: &executable-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -O2

executables:
  new-module:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - create-module
    ghc-options: *executable-ghc-options

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - create-module
      - HUnit
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-hunit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4

